name: my first workflow

on: push

# my first github workflow

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
              
            - name: list and Read file
              run: |
                echo "my first Github Actions Job"
                ls
                cat README.md
            - name: Generate ASCII Artwork
              run: cowsay -f dragon "RUN for cover, I am a DRAGON...RAWR" >>dragon.txt




            # - name: List files
            #   run: ls
            # - name: Read file
            #   run: cat README.md

            # runs-on: ubuntu-latest
        # steps:
        # - name: checkout repo
        #   uses: actions/checkout@v4

        # - name: List Repo Files
        #   run: ls -ltra
          
        # - name: Executing shell script
        #   run: |
        #     chmod +x .github/workflows/ascii-script.sh 
        #     .github/workflows/ascii-script.sh
    