name: my first workflow

on: push

# my first github workflow

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4

            - name: list and Read file
              run: |
                echo "my first Github Actions Job"
                ls
                cat README.md
            - name: Generate ASCII Artwork
              run: cowsay -f dragon "RUN for cover, I am a DRAGON...RAWR" >>dragon.txt