name: Matrix Configuration

on:
    push:
    workflow_dispatch:

jobs:
    deploy-on-ubuntu:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest] 
                images: [hello-world,alpine]
        steps:
        - name: Echo Dockmer Details
          run: docker info
        
        - name: Run Image ${{ matrix.os }}
          run: docker run ${{ matrix.images }}